version: "3.7"

services:
  test:
    container_name: react-app-test
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    command: yarn test:coverage 

  security:
    container_name: security
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    command: yarn audit --groups dependencies

  lint:
    container_name: react-app-lint
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    command: yarn lint